### ISSUE TITLE
Performance evaluation of finetuned models

### ISSUE THREAD

**Issue by Kostis-S-Z** [mozilla-ai/speech-to-text-finetune#43]
We should evaluate finetuning whisper tiny and small on a few languages to see in which case there is degradation, improvement or no effect. Evaluation results are tracked [here](https://docs.google.com/spreadsheets/d/1NWCGon4hQH4lqr-aBa66dJ6828JfNXwlh6emgzRoEP4/edit?gid=0#gid=0) [mozilla.ai access only]

Example config should look like this:

```
model_id: openai/whisper-small
dataset_id: mozilla-foundation/common_voice_17_0
dataset_source: HF
language: Italian
repo_name: default

training_hp:
    push_to_hub: True
    hub_private_repo: True
    max_steps: 2000
    per_device_train_batch_size: 32
    gradient_accumulation_steps: 1
    learning_rate: 1e-5
    warmup_steps: 50
    gradient_checkpointing: True
    fp16: True  # If a GPU is available, set it to True for faster training & decreased memory usage -> bigger batches
    eval_strategy: steps
    per_device_eval_batch_size: 8
    predict_with_generate: True
    generation_max_length: 225
    save_steps: 50
    logging_steps: 25
    load_best_model_at_end: True
    metric_for_best_model: wer
    greater_is_better: False

```
